services:
  # client:
  #   image: rhythm_game-client:latest
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.client
  #   ports:
  #     - "5000:80"
    # depends_on:
    #   - server
  server:
    image: rhythm-game_server:latest
    build:
      context: ./
      dockerfile: Dockerfile.server
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      PG_HOST: pg
      PG_PORT: 5432
    ports:
      - "3000:80"
  pg:
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pg-data:
    external: true
    name: da6044db31cae4a77873422d2eb37da0ac6568bfb898d5efbfa05ca268e834ae
  redis-data:
    external: true
    name: 0774945432b915ad6145ae6fe86723cf867fb915ef31d5a6c7dbbf118e2cb087

# apk add curl
# docker compose up -d