services:
  client:
    image: rhythm_game-client:latest
    build:
      context: ./
      dockerfile: Dockerfile.client
    env_file:
      - .env
    ports:
      - "5000:80"
    depends_on:
      - server
  server:
    image: rhythm-game_server:latest
    build:
      context: ./
      dockerfile: Dockerfile.server
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:80"
  pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

# apk add curl
# docker compose up -d